name: elf
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - numpy<2.0
  - pandas
  - polars
  - scikit-learn
  - scipy>=1.13,<1.15
  - opencv
  - pillow>=10.2,<13
  - pydantic
  - rich
  - git-lfs
  - pip:
      - accelerate>=0.26,<1.0
      - albumentations>=2.0
      - bitsandbytes
      - datasets
      - diffusers
      - einops
      - evaluate
      - fastapi
      - gradio
      - huggingface-hub>=0.20,<1.0
      - kornia>=0.7
      - lycoris-lora>=3.0
      - omegaconf>=2.3
      - optimum-quanto>=0.2
      - peft
      - prodigyopt
      - safetensors
      - tensorboard>=2.14
      - timm
      - toml
      - transformers==4.49.0
      - uvicorn
      - wandb
      - xformers
      - rembg
      - fiftyone
      - onnxruntime
      - optuna
      - sentencepiece
      - tokenizers>=0.20,<1.0
      - tqdm
